### ISSUE TITLE
node specific calls

### ISSUE THREAD

**Issue by iamyellow** [hyperswarm/libudx#94]
hey! writing this issue just to keep track.

In order to have *portable* js we would need to find isomorphic (is that the official naming?) solutions or having our own.

eg. in `react-native` we don't have:
- util https://github.com/hyperswarm/libudx/blob/093f0a88ba714c907214b343cfb6f3822cd1140e/lib/udx.js#L1
- events https://github.com/hyperswarm/libudx/blob/7b190cb6d6c0470dfa82c29b66fd7c14dbd39092/lib/socket.js#L1
- ` Error.captureStackTrace` https://github.com/hyperswarm/libudx/blob/093f0a88ba714c907214b343cfb6f3822cd1140e/lib/udx.js#L84
- `Buffer.allocUnsafe` https://github.com/hyperswarm/libudx/blob/6d541cdc75baa0dcd3477255019633a393417eee/lib/stream.js#L294

some shims / polyfills do exist, but you know...

**Comment by kasperisager** [comment]
I've opened #97, #98, and #99 to deal with these.

**Comment by mafintosh** [comment]
merged!

**Comment by mafintosh** [comment]
We fixed this
